name: DevSecOps Pipeline

on:
  push:
    branches: [ devsecops-pipeline, main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # Force l'exécution à la racine
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Optionnel : accélère vos futurs pipelines
          
      - name: Install dependencies
        run: npm install
        
      - name: Run unit tests
        run: npm test
